#!/usr/bin/env bash
#changing 8th and 4th output
n=1
while [ $n -le 10 ]
do 
  if [ $n = 4 ]
  then 
      echo "bad luck"
  elif [ $n = 8 ]
  then 
     echo "good luck"
  else
     echo "Best School"
  fi
  ((n++))
done
